version: '3.7'
services:
  frontend:
    image: jhamilton31/frontend:latest
    build: ./frontend
    depends_on:
      - backend

  backend:
    image: jhamilton31/backend:latest
    build: ./backend
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URI: ${DATABASE_URI}
      TEST_DATABASE_URI: ${TEST_DATABASE_URI}
    depends_on:
      - mysql

  mysql:
    image: mysql
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend