version: "3.8"
services:
  frontend:
    container_name: frontend
    image: jhamilton31/frontend:latest
    ports:
      - target: 5000
        published: 5000
    depends_on:
      - backend

  backend:
    container_name: backend
    image: jhamilton31/backend:latest
    ports:
      - target: 5001
        published: 5001
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - TEST_DATABASE_URI=${TEST_DATABASE_URI}
      - SECRET_KEY=${SECRET_KEY}

  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend

  mysql:
    image: mysql
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}